version: '3'
services:
  uruk-back:
    build:
      context: .
    image: tihomir619/academiafiremd
    ports:
      - '3005:3000'
    environment:
      DATABASE_URL: ${DATABASE_URL}
    restart: always
